apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: list-pods-binding
  namespace: NAMESPACE_NAME
subjects:
- kind: ServiceAccount
  name: KSA_NAME
  namespace: NAMESPACE_NAME
roleRef:
  kind: Role
  name: list-pods-role
  apiGroup: rbac.authorization.k8s.io
